### ISSUE TITLE
Always exit with status 0

### ISSUE THREAD

**Issue by samirchian** [grosser/parallel_split_test#16]
even tests are failing but the exit code is 0.
 `results.map(&:first).max # combine exit status` I am not sure if this line is doing what is suppose to do. 
Please advice.

**Comment by grosser** [comment]
`puts results.inspect` to see what it got ?
... can you reproduce with a very simple setup ? ... ideally build a failing test for the repo.

**Comment by samirchian** [comment]
```
Summary:
2 examples, 1 failure
1 example, 0 failures
1 example, 1 failure
1 example, 0 failures
1 example, 0 failures
1 example, 0 failures
1 example, 0 failures
1 example, 1 failure
--------------result first --------------
1
0
1
0
0
0
0
1
--------------end result first --------------
--------------exit code--------------
1
--------------end exit code--------------
```

it is returning 1 but still exit as success. Maybe the issue is in Parallel ?

**Comment by grosser** [comment]
exit code is 1 ... so everything works ...
what is your `echo $?` after running the command ? ... what command are you running ?
... it ends up with an `exit 1` so everything should be fine ...

**Comment by samirchian** [comment]
the command is `system('rake test_configurations:osx_10_chrome_54')` and the output of `$?` is  
```
Summary:
2 examples, 1 failure
1 example, 0 failures
1 example, 1 failure
1 example, 0 failures
1 example, 0 failures
1 example, 0 failures
1 example, 0 failures
1 example, 1 failure
Took 96.01 seconds with 8 processes
pid 34266 exit 0
```

**Comment by grosser** [comment]
... but what does `rake test_configurations:osx_10_chrome_54` do ? :D

**Comment by samirchian** [comment]
```
system( parallel_split_test spec/features" )
```

**Comment by grosser** [comment]
... that will never fail ...

```
sh "parallel_split_test spec/features"
exec "parallel_split_test spec/features"
abort unless system("parallel_split_test spec/features")
```

**Comment by samirchian** [comment]
@grosser thanks I had rescue but in wrong place!!
