### ISSUE TITLE
Same thread number

### ISSUE THREAD

**Issue by serhatbolsu** [grosser/parallel_split_test#18]
I am using allure reporting along with this gem; 
Allure report generate thread number same with all reports (each parallel executor report). This is not happening like this with parallel_tests

Below is the code where allure gets the thread id:
https://github.com/allure-framework/allure-ruby-commons/blob/master/lib/allure-ruby-adaptor-api/builder.rb
```
      def add_default_labels(labels = {})
        labels[:thread] ||= Thread.current.object_id
        labels[:host] ||= HOSTNAME
        labels
      end
```

Is it possible all running under same thread ? or how can I make a change to differentiate the thread number?

**Comment by grosser** [comment]
Thread.current.object_id looks correct ... 
do something like `before { puts Thread.current.object_id }` to see if all tests run in the same thread

**Comment by serhatbolsu** [comment]
Actually this is the log

All of the processes seems to be using the same thread,
```
Running examples in 2 processes
Cleaning output directory 'allure-results'...
<<!!! Starting session : 70212401700880 >>
"/Users/serhatbolsu/repos/pf-quality/manager-web/spec/../screenshots"
Cleaning output directory 'allure-results'...
<<!!! Starting session : 70212401700880 >>
"/Users/serhatbolsu/repos/pf-quality/manager-web/spec/../screenshots"
<<!!! Starting session : 70212401700880 >>
"/Users/serhatbolsu/repos/pf-quality/manager-web/spec/../screenshots"
<<!!! Starting session : 70212401700880 >>
"/Users/serhatbolsu/repos/pf-quality/manager-web/spec/../screenshots"
<<!!! Starting session : 70212401700880 >>
"/Users/serhatbolsu/repos/pf-quality/manager-web/spec/../screenshots"
<<!!! Starting session : 70212401700880 >>
"/Users/serhatbolsu/repos/pf-quality/manager-web/spec/../screenshots"
```

**Comment by grosser** [comment]
runs in multiple processes and not threads ... so print `Process.pid` and it will be different :)
