### ISSUE TITLE
Undefined method `prepare_example_filtering'

### ISSUE THREAD

**Issue by AravindSelvamani** [grosser/parallel_split_test#24]
**Run command:** `parallel_split_test spec/parallel_split_test_spec.rb`

`.rvm/gems/ruby-2.5.1/gems/parallel_split_test-0.9.0/lib/parallel_split_test/core_ext/rspec_world.rb:5:in `block in <top (required)>': undefined method `prepare_example_filtering' for class `RSpec::Core::World' (NameError)`

Ruby version: 2.5.1

**Comment by grosser** [comment]
rspec version ?

**Comment by AravindSelvamani** [comment]
RSpec 3.7 @grosser

**Comment by grosser** [comment]
update rspec to >= 3.9, that's what the tests run with here

**Comment by grosser** [comment]
I released a new version that required 3.9 so nobody runs into that again
