### ISSUE TITLE
CommandLine Error

### ISSUE THREAD

**Issue by prolificcoder** [grosser/parallel_split_test#3]
/Library/Ruby/Gems/2.0.0/gems/parallel_split_test-0.3.0/lib/parallel_split_test/command_line.rb:8:in `<module:ParallelSplitTest>': uninitialized constant RSpec::Core::CommandLine (NameError)

**Comment by bootstraponline** [comment]
It'd be nice to see the 'split test' feature integrated into the parallel_tests gem as an optional flag.

**Comment by grosser** [comment]
it's a completely different approach, that is why this is a different gem :)

**Comment by bootstraponline** [comment]
Makes sense. PR sent.
