### ISSUE TITLE
Option to disable summary

### ISSUE THREAD

**Issue by bootstraponline** [grosser/parallel_split_test#5]
[reprint_result_lines](https://github.com/grosser/parallel_split_test/blob/21d73098a607fd1b733896b8a1142bdba3869a7f/lib/parallel_split_test/command_line.rb#L70) always prints a summary. Gems that search for `"1 example, 0 failures"` such as the parallel_tests gem

> @runner.find_results(test_results.map { |result| result[:stdout] }*"")

will double count the results since they exist twice in the output. It'd be great if there was an option to disable summary output.

**Comment by grosser** [comment]
I did not imagine these 2 projects to be used together oO

Please make a PR if you have a solution in mind.

**Comment by bootstraponline** [comment]
I've submitted a PR. I'm dynamically patching parallel_tests to use parallel_split_test since there isn't any other way to get parallel_tests working at the individual test level.

**Comment by grosser** [comment]
does running parallel_split_test with multiple files not work ? <-> why is parallel_tests needed ?

**Comment by bootstraponline** [comment]
> does running parallel_split_test with multiple files not work ?

It does.

> why is parallel_tests needed ?

Sauce Labs has an old heavily monkey patched parallel_tests which is why [parallel_split_test](https://github.com/saucelabs/sauce_ruby/commit/006b205f02f3d63ebf43a6248a7b620488659cd8) is used in combination with parallel_tests. One day sauce_ruby will be refactored then it'll be easier to isolate the dependencies and not monkey patch everything.

**Comment by grosser** [comment]
sounds like you are having a good time :D
