### ISSUE TITLE
Clarification needed for what happens with before :all

### ISSUE THREAD

**Issue by sbonebrake** [grosser/parallel_split_test#7]
I noticed that when running with parallel_split_test, every example group will attempt to run the "before :all" context even if "run_example?" is calculated false for the process later.  
This causes two problems:
1. The "before :all" contexts will be run once in every process.
2. If some of the "before :all" contexts encounter an error then it will report failure for that example. This will result in multiple results for an example in a single run.

Is anyone else seeing this?  I'm not sure if this is intended and a known limitation or not. If it is, the ReadMe should be updated.  If it's not intended, then we should investigate alternatives.

**Comment by bootstraponline** [comment]
My understanding is that parallel_split_test executes each test in a separate process thus the before :all will always run. It'd be the same if you manually invoked rspec with the -e flag.

If you have two tests and they're each in a separate process, I'm not sure how you'd run before :all in one and not the other. Most people use [parallel_tests](https://github.com/grosser/parallel_tests) to parallelize at the file level to avoid issues like that. The trade off is the tests will run slower because all tests in a file execute serially.

Maybe grosser will have some more info however my guess is this is a "feature" not a bug.

**Comment by sbonebrake** [comment]
I would hope that the before :all would only execute if the current process contains an example from inside the at before :all, rather than in each process. 
Example:
big_spec.rb has
```
  before :all 
    # Some expensive operation
  end
  it "big one" {...}
  it "big two" {...}
  it "big three" {...}
```
and there is another small_spec.rb with:
```
  before :each
    # Some fast operation
  end
  it "small one" {...}
  it "small two" {...}
  it "small three" {...}
```
If there are 3 processes, the assignment will look like:
```
Process #1: ["big_spec's before :all", "big one", "small_spec's before :each", "small one"]
Process #2: ["big_spec's before :all", "big two", "small_spec's before :each", "small two"]
Process #3: ["big_spec's before :all", "big three", "small_spec's before :each", "small three"]
```
This works out fine. However, if there are 6 processes, 3 of them will unnecessarily execute big_spec's before :all.
```
Process #1: ["big_spec's before :all", "big one"]
Process #2: ["big_spec's before :all", "big two"]
Process #3: ["big_spec's before :all", "big three"]
Process #4: ["big_spec's before :all", "small_spec's before :each", "small one"]
Process #5: ["big_spec's before :all", "small_spec's before :each", "small two"]
Process #6: ["big_spec's before :all", "small_spec's before :each", "small three"]
```
I apologize if i'm not fully grasping the rspec terminology.  It seems to me that that "big_spec's before :all" should only be executed on processes that will execute a test in that example group.  This will still result in multiple executions of it, but at least every process won't execute it.  Am I making any sense or am I way off?

**Comment by bootstraponline** [comment]
Oh, I understand now. I agree, that seems like a bug. I would expect the before all to be scoped to the describe block. If you just use rspec with serial execution, is the behavior any different? If rspec works as expected then it should be possible to fix up parallel_split_test.

**Comment by grosser** [comment]
this might be due to the skipping of individual examples, rspec still thinks we run the whole block and the we skip all the examples

**Comment by sbonebrake** [comment]
Yes, I believe that's it. Right now, each example basically decides for itself if it's going to actually run using the ParallelSplitTest.run_example?(self) call. This occurs after the contexts have already been run because it thinks they're going to run. 
I'm tinkering around with alternate strategies right now.  Rather than have each example figure out if it's actually going to run at execution time, does it make sense to split up the tests beforehand?  
Right now I'm able to:
  1. load_spec_files
  2. extract the example ids
  3. put the id's in roughly equal buckets
  4. format the id strings as filter_manager rules

At this point I'm not sure where to go next.  Ideally each process would just work with its own copy of filter manager, but some things appear to have already been set in world and configuration. Maybe some combination of configuration.reset or world.reset is what's needed.  If we are able to assign the specific example ids to processes, then eventually we could try strategies other than an even split, such as splitting based on previous run time.

**Comment by schneems** [comment]
Hey. I'm hitting this issue as well. I'm doing something VERY expensive in the `before(:all)` block scoped to just a single describe block, expecting it to only run once in the process where those tests run, but instead the describe block fires for all processes even if they don't execute a test from that describe block:


## Repro

The "foo" describe block only has one test, the `before(:all)` for it should only be run once:

```ruby
  describe "foo" do
    before(:all) do
      puts "before(:all) foo"
    end

    it "blerg" do
    end
  end
```

Install:

```
$ git clone https://github.com/schneems/rspec_test_project
$ bundle
```

Actual:


```
$ PARALLEL_SPLIT_TEST_PROCESSES=5 bundle exec parallel_split_test spec/ | grep "before(:all) foo"
before(:all) foo
before(:all) foo
before(:all) foo
before(:all) foo
before(:all) foo
```

However it gets executed for every process even though only one process is only executing it's tests.

**Comment by schneems** [comment]
I'm digging into the code and I see why this is happening now. This is how the runner selectively runs tests:

```
require 'parallel_split_test'
require 'rspec/core/example'

RSpec::Core::Example.class_eval do
  alias :run_without_parallel_split_test :run
  def run(*args, &block)
    if ParallelSplitTest.run_example?
      run_without_parallel_split_test(*args, &block)
    else
      true # example 'passed'
    end
  end
end
```

Rspec thinks it's running each test, however this gem selectively skips each test at the last second.

**Comment by grosser** [comment]
I think this still prevents the `before :each` calls, but for `before :all` it would need some new logic to say "are all tests in this block skipped?" ... not sure how hard to do that is

workaround could be instal of using a `before :all` to do a `@@foobar ||= expensive` in each `it` or `before`
but definitely prefer a PR to fix this

**Comment by schneems** [comment]
I think what we need to do is find someplace earlier to clear out examples. As a short term hack, this seems to work:

```
RSpec::Core::World.class_eval do
  alias :original_prepare_example_filtereing :prepare_example_filtering

  def prepare_example_filtering
    @parallel_split_test_example_counter = 0

    @original_filtered_examples = original_prepare_example_filtereing
    @filtered_examples = Hash.new do |hash, group|
      hash[group] = @original_filtered_examples[group].select do |x|
        @parallel_split_test_example_counter += 1
        (@parallel_split_test_example_counter - 1) % ::ParallelSplitTest.processes == ::ParallelSplitTest.process_number
      end
    end
  end

```

I'm not sure how "safe" that is though. `prepare_example_filtering` is a public API. It looks like it does the trick for the short term. I'll try to work that into a PR and see if tests pass.

**Comment by schneems** [comment]
It did not pass out of the box. I don't know how much of this is due to an innate problem with my above logic versus implicit assumptions:

```
28 examples, 7 failures

Failed examples:

rspec ./spec/parallel_split_test_spec.rb:90 # ParallelSplitTest cli running tests runs in different processes
rspec ./spec/parallel_split_test_spec.rb:109 # ParallelSplitTest cli running tests runs in different processes for many examples/processes
rspec ./spec/parallel_split_test_spec.rb:141 # ParallelSplitTest cli running tests splits based on examples
rspec ./spec/parallel_split_test_spec.rb:162 # ParallelSplitTest cli running tests fails when one of the processes fail
rspec ./spec/parallel_split_test_spec.rb:176 # ParallelSplitTest cli running tests fails when all processes fail
rspec ./spec/parallel_split_test_spec.rb:225 # ParallelSplitTest cli running tests reprints all summary lines at the end
rspec ./spec/parallel_split_test_spec.rb:248 # ParallelSplitTest cli running tests writes a unified --out
```

**Comment by schneems** [comment]
I've got a proposed solution in https://github.com/grosser/parallel_split_test/pull/20

**Comment by grosser** [comment]
0.8.0
